name: EKS Cluster

on:
    workflow_dispatch: 

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: self-hosted

   

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Plan Terraform Changes
      - name: Terraform Init
        run: terraform init

      # Step 3: Apply Terraform Changes
      - name: Terraform Apply
        run: terraform destroy -auto-approve
