name: EKS Cluster Deletion

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: self-hosted

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Initialize Terraform
      - name: Terraform Init
        run: terraform init

     

      # Step 4: Destroy Terraform Changes
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
